import mongoose, { Document, Schema } from "mongoose";

export interface IMailDocument extends Document {
    userId: string;
    from: string;
    to: string;
    cc?: string;
    bcc?: string;
    subject: string;
    content: string;
    status: "SENT" | "FAILED" | "PENDING";
    direction?: "INBOUND" | "OUTBOUND";
    providerMessageId?: string;
    providerThreadId?: string;
    inReplyTo?: string;
    autoRepliedAt?: Date;
    autoReplyStatus?: "SKIPPED" | "DRAFTED" | "SENT" | "BLOCKED";
    autoReplyReason?: string;
    intentTag?: "Complaint" | "Inquiry" | "Follow-up" | "Spam-like";
    intentConfidence?: number;
    isAutoGenerated?: boolean;
    tone?: string;
    language?: string;
    scheduledAt?: Date;
    openedAt?: Date;
    repliedAt?: Date;
    createdAt: Date;
}

const MailSchema = new Schema<IMailDocument>({
    userId: { type: String, required: true, index: true },
    from: { type: String, required: true },
    to: { type: String, required: true },
    cc: { type: String },
    bcc: { type: String },
    subject: { type: String, required: true },
    content: { type: String, required: true },
    status: { type: String, enum: ["SENT", "FAILED", "PENDING"], default: "PENDING" },
    direction: { type: String, enum: ["INBOUND", "OUTBOUND"], default: "OUTBOUND" },
    providerMessageId: { type: String, index: true },
    providerThreadId: { type: String, index: true },
    inReplyTo: { type: String },
    autoRepliedAt: { type: Date },
    autoReplyStatus: { type: String, enum: ["SKIPPED", "DRAFTED", "SENT", "BLOCKED"] },
    autoReplyReason: { type: String },
    intentTag: { type: String, enum: ["Complaint", "Inquiry", "Follow-up", "Spam-like"] },
    intentConfidence: { type: Number },
    isAutoGenerated: { type: Boolean, default: false },
    tone: { type: String },
    language: { type: String },
    scheduledAt: { type: Date },
    openedAt: { type: Date },
    repliedAt: { type: Date },
    createdAt: { type: Date, default: Date.now },
});

export const Mail = mongoose.model<IMailDocument>("Mail", MailSchema);
