export interface IMailEntity {
    id?: string;
    userId: string;
    from: string;
    to: string;
    cc?: string;
    bcc?: string;
    subject: string;
    content: string;
    status: "SENT" | "FAILED" | "PENDING";
    direction?: "INBOUND" | "OUTBOUND";
    providerMessageId?: string;
    providerThreadId?: string;
    inReplyTo?: string;
    autoRepliedAt?: Date;
    autoReplyStatus?: "SKIPPED" | "DRAFTED" | "SENT" | "BLOCKED";
    autoReplyReason?: string;
    isAutoGenerated?: boolean;
    tone?: string;
    language?: string;
    scheduledAt?: Date;
    openedAt?: Date;
    repliedAt?: Date;
    createdAt?: Date;
}

export interface IMailRepository {
    create(mail: IMailEntity): Promise<IMailEntity>;
    findById(id: string): Promise<IMailEntity | null>;
    findByUserId(userId: string): Promise<IMailEntity[]>;
    findDueScheduled(now: Date, limit?: number): Promise<IMailEntity[]>;
    updateStatus(id: string, status: "SENT" | "FAILED" | "PENDING"): Promise<IMailEntity | null>;
    markOpened(id: string): Promise<void>;
    markReplied(id: string): Promise<void>;
    findByProviderMessageId(providerMessageId: string, userId: string): Promise<IMailEntity | null>;
    findInboundForReview(userId: string, limit?: number): Promise<IMailEntity[]>;
    findRecentAutoReplyByThread(userId: string, providerThreadId: string, since: Date): Promise<IMailEntity | null>;
    findLatestAutoReplyForInbound(userId: string, providerMessageId?: string, providerThreadId?: string): Promise<IMailEntity | null>;
    updateAutoReplyResult(id: string, status: "SKIPPED" | "DRAFTED" | "SENT" | "BLOCKED", reason?: string): Promise<void>;
    markAutoReplied(id: string): Promise<void>;
}
