import { IMailRepository, IMailEntity } from "../interfaces/repositories/IMailRepository";
import { Mail } from "../models/MailModel";

function toEntity(mail: any): IMailEntity {
    return {
        id: mail._id.toString(),
        userId: mail.userId,
        from: mail.from,
        to: mail.to,
        cc: mail.cc,
        bcc: mail.bcc,
        subject: mail.subject,
        content: mail.content,
        status: mail.status,
        direction: mail.direction,
        providerMessageId: mail.providerMessageId,
        providerThreadId: mail.providerThreadId,
        inReplyTo: mail.inReplyTo,
        autoRepliedAt: mail.autoRepliedAt,
        autoReplyStatus: mail.autoReplyStatus,
        autoReplyReason: mail.autoReplyReason,
        isAutoGenerated: mail.isAutoGenerated,
        tone: mail.tone,
        language: mail.language,
        scheduledAt: mail.scheduledAt,
        openedAt: mail.openedAt,
        repliedAt: mail.repliedAt,
        createdAt: mail.createdAt,
    };
}

export class MongoMailRepository implements IMailRepository {
    async create(mail: IMailEntity): Promise<IMailEntity> {
        const newMail = new Mail({
            userId: mail.userId,
            from: mail.from,
            to: mail.to,
            cc: mail.cc,
            bcc: mail.bcc,
            subject: mail.subject,
            content: mail.content,
            status: mail.status || "PENDING",
            direction: mail.direction || "OUTBOUND",
            providerMessageId: mail.providerMessageId,
            providerThreadId: mail.providerThreadId,
            inReplyTo: mail.inReplyTo,
            autoRepliedAt: mail.autoRepliedAt,
            autoReplyStatus: mail.autoReplyStatus,
            autoReplyReason: mail.autoReplyReason,
            isAutoGenerated: mail.isAutoGenerated || false,
            tone: mail.tone,
            language: mail.language,
            scheduledAt: mail.scheduledAt,
        });
        const savedMail = await newMail.save();
        return toEntity(savedMail.toObject());
    }

    async findById(id: string): Promise<IMailEntity | null> {
        const mail = await Mail.findById(id).lean();
        if (!mail) return null;
        return toEntity(mail);
    }

    async findByUserId(userId: string): Promise<IMailEntity[]> {
        const mails = await Mail.find({ userId }).sort({ createdAt: -1 }).lean();
        return mails.map(toEntity);
    }

    async findDueScheduled(now: Date, limit = 20): Promise<IMailEntity[]> {
        const mails = await Mail.find({
            status: "PENDING",
            scheduledAt: { $lte: now, $ne: null },
        })
            .sort({ scheduledAt: 1 })
            .limit(limit)
            .lean();
        return mails.map(toEntity);
    }

    async updateStatus(id: string, status: "SENT" | "FAILED" | "PENDING"): Promise<IMailEntity | null> {
        const mail = await Mail.findByIdAndUpdate(id, { status }, { new: true }).lean();
        if (!mail) return null;
        return toEntity(mail);
    }

    async markOpened(id: string): Promise<void> {
        await Mail.findByIdAndUpdate(id, { openedAt: new Date() });
    }

    async markReplied(id: string): Promise<void> {
        await Mail.findByIdAndUpdate(id, { repliedAt: new Date() });
    }

    async findByProviderMessageId(providerMessageId: string, userId: string): Promise<IMailEntity | null> {
        const mail = await Mail.findOne({ providerMessageId, userId }).lean();
        return mail ? toEntity(mail) : null;
    }

    async findInboundForReview(userId: string, limit = 50): Promise<IMailEntity[]> {
        const mails = await Mail.find({ userId, direction: "INBOUND" }).sort({ createdAt: -1 }).limit(limit).lean();
        return mails.map(toEntity);
    }

    async findRecentAutoReplyByThread(userId: string, providerThreadId: string, since: Date): Promise<IMailEntity | null> {
        const mail = await Mail.findOne({
            userId,
            providerThreadId,
            direction: "OUTBOUND",
            isAutoGenerated: true,
            createdAt: { $gte: since },
        })
            .sort({ createdAt: -1 })
            .lean();
        return mail ? toEntity(mail) : null;
    }

    async updateAutoReplyResult(id: string, status: "SKIPPED" | "DRAFTED" | "SENT" | "BLOCKED", reason?: string): Promise<void> {
        await Mail.findByIdAndUpdate(id, {
            autoReplyStatus: status,
            autoReplyReason: reason || undefined,
        });
    }

    async markAutoReplied(id: string): Promise<void> {
        await Mail.findByIdAndUpdate(id, { autoRepliedAt: new Date(), autoReplyStatus: "SENT" });
    }
}
